from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Union

import joblib
import numpy as np
import pandas as pd


# ============================================================================
# PROJECT PATHS
# ============================================================================

PROJECT_DIR = Path(__file__).resolve().parent

MODEL_DIR = PROJECT_DIR / "saved_models" / "real_firms_v1"

THRESHOLD_CONFIG_PATH = (
    PROJECT_DIR
    / "data"
    / "retraining"
    / "real_firms_threshold_config_v1.json"
)


# ============================================================================
# APPROVED MODEL FILES
# ============================================================================

MODEL_FILES = {
    "24h": MODEL_DIR / "fireguard_real_firms_sensor_only_24h_v1.joblib",
    "48h": MODEL_DIR / "fireguard_real_firms_sensor_only_48h_v1.joblib",
    "72h": MODEL_DIR / "fireguard_real_firms_sensor_only_72h_v1.joblib",
}


# ============================================================================
# REQUIRED PRODUCTION FEATURES
# ============================================================================
# This order MUST remain identical to the trained model schema.
# ============================================================================

FEATURE_COLUMNS = [
    "latitude",
    "longitude",
    "brightness",
    "scan",
    "track",
    "confidence",
    "bright_t31",
    "frp",
    "hour",
    "minute",
    "daynight_encoded",
    "satellite_encoded",
    "instrument_encoded",
    "type_encoded",
    "season_encoded",
]


BASE_REQUIRED_COLUMNS = [
    "latitude",
    "longitude",
    "brightness",
    "scan",
    "track",
    "confidence",
    "bright_t31",
    "frp",
]


# ============================================================================
# INTERNAL HELPERS
# ============================================================================

def _find_first_column(
    dataframe: pd.DataFrame,
    candidates: Iterable[str],
) -> Union[str, None]:
    """
    Return the first existing column name from candidates.
    """

    for column in candidates:
        if column in dataframe.columns:
            return column

    return None


def _normalize_text(series: pd.Series) -> pd.Series:
    """
    Normalize text safely without modifying the source dataframe.
    """

    return (
        series.astype(str)
        .fillna("")
        .str.strip()
        .str.upper()
    )


def _encode_categorical(
    series: pd.Series,
    mapping: Dict[str, int],
    default_value: int = -1,
) -> pd.Series:
    """
    Convert known categorical values to stable integer codes.

    Unknown values receive default_value.
    """

    normalized = _normalize_text(series)

    return (
        normalized.map(mapping)
        .fillna(default_value)
        .astype(int)
    )


def _extract_model(saved_object: Any) -> Any:
    """
    Extract the actual sklearn-compatible model from a saved object.

    Existing training artifacts may contain either:
        - the model directly
        - a dictionary containing the model

    No saved object is modified.
    """

    if hasattr(saved_object, "predict_proba"):
        return saved_object

    if isinstance(saved_object, dict):

        preferred_keys = [
            "model",
            "pipeline",
            "estimator",
            "classifier",
        ]

        for key in preferred_keys:

            candidate = saved_object.get(key)

            if hasattr(candidate, "predict_proba"):
                return candidate

        for value in saved_object.values():

            if hasattr(value, "predict_proba"):
                return value

    raise TypeError(
        "Could not find a prediction model with predict_proba() "
        f"inside saved object of type: {type(saved_object).__name__}"
    )


def _extract_thresholds(config: Dict[str, Any]) -> Dict[str, float]:
    """
    Extract approved thresholds from the existing configuration.

    Supports the structure generated by the previous FIREGUARD threshold
    configuration script.
    """

    threshold_source = config.get("thresholds", config)

    aliases = {
        "24h": ["24h", "24H", "fire_next_24h"],
        "48h": ["48h", "48H", "fire_next_48h"],
        "72h": ["72h", "72H", "fire_next_72h"],
    }

    thresholds: Dict[str, float] = {}

    for horizon, keys in aliases.items():

        value = None

        for key in keys:

            if key in threshold_source:
                value = threshold_source[key]
                break

        if isinstance(value, dict):

            for nested_key in ["threshold", "value"]:

                if nested_key in value:
                    value = value[nested_key]
                    break

        if value is None:
            raise KeyError(
                f"Threshold for {horizon} not found in configuration."
            )

        try:
            value = float(value)
        except (TypeError, ValueError) as error:
            raise ValueError(
                f"Invalid threshold for {horizon}: {value!r}"
            ) from error

        if not 0.0 <= value <= 1.0:
            raise ValueError(
                f"Threshold for {horizon} must be between 0 and 1. "
                f"Received: {value}"
            )

        thresholds[horizon] = value

    return thresholds


# ============================================================================
# FEATURE PREPARATION
# ============================================================================

def prepare_real_firms_features(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """
    Prepare the exact production feature matrix required by the
    approved REAL FIRMS models.

    Important:
        - Input dataframe is NOT modified.
        - Derived encoded columns exist only in the returned dataframe.
        - Output column order is fixed to FEATURE_COLUMNS.
    """

    if not isinstance(dataframe, pd.DataFrame):
        raise TypeError(
            "Input must be a pandas DataFrame."
        )

    if dataframe.empty:
        raise ValueError(
            "Input dataframe is empty."
        )

    missing_base = [
        column
        for column in BASE_REQUIRED_COLUMNS
        if column not in dataframe.columns
    ]

    if missing_base:
        raise ValueError(
            "Required base columns missing: "
            + ", ".join(missing_base)
        )

    working = dataframe.copy()

    # ------------------------------------------------------------------------
    # Numeric base features
    # ------------------------------------------------------------------------

    for column in BASE_REQUIRED_COLUMNS:

        working[column] = pd.to_numeric(
            working[column],
            errors="coerce",
        )

    # ------------------------------------------------------------------------
    # Time features
    # ------------------------------------------------------------------------
    # Prefer existing hour/minute.
    # If unavailable, attempt to derive from common datetime columns.
    # ------------------------------------------------------------------------

    if "hour" not in working.columns or "minute" not in working.columns:

        datetime_column = _find_first_column(
            working,
            [
                "detection_timestamp",
                "acq_datetime",
                "datetime",
                "timestamp",
                "date_time",
            ],
        )

        if datetime_column is not None:

            parsed_datetime = pd.to_datetime(
                working[datetime_column],
                errors="coerce",
            )

            if "hour" not in working.columns:
                working["hour"] = parsed_datetime.dt.hour

            if "minute" not in working.columns:
                working["minute"] = parsed_datetime.dt.minute

        else:

            if "hour" not in working.columns:
                working["hour"] = 0

            if "minute" not in working.columns:
                working["minute"] = 0

    working["hour"] = pd.to_numeric(
        working["hour"],
        errors="coerce",
    )

    working["minute"] = pd.to_numeric(
        working["minute"],
        errors="coerce",
    )

    # ------------------------------------------------------------------------
    # daynight_encoded
    # ------------------------------------------------------------------------

    if "daynight_encoded" in working.columns:

        working["daynight_encoded"] = pd.to_numeric(
            working["daynight_encoded"],
            errors="coerce",
        )

    else:

        daynight_column = _find_first_column(
            working,
            [
                "daynight",
                "day_night",
            ],
        )

        if daynight_column is not None:

            working["daynight_encoded"] = _encode_categorical(
                working[daynight_column],
                {
                    "D": 0,
                    "DAY": 0,
                    "N": 1,
                    "NIGHT": 1,
                },
                default_value=-1,
            )

        else:

            working["daynight_encoded"] = -1

    # ------------------------------------------------------------------------
    # satellite_encoded
    # ------------------------------------------------------------------------

    if "satellite_encoded" in working.columns:

        working["satellite_encoded"] = pd.to_numeric(
            working["satellite_encoded"],
            errors="coerce",
        )

    else:

        satellite_column = _find_first_column(
            working,
            [
                "satellite",
            ],
        )

        if satellite_column is not None:

            working["satellite_encoded"] = _encode_categorical(
                working[satellite_column],
                {
                    "AQUA": 0,
                    "TERRA": 1,
                    "SNPP": 2,
                    "SUOMI NPP": 2,
                    "NOAA-20": 3,
                    "NOAA20": 3,
                    "JPSS-1": 3,
                },
                default_value=-1,
            )

        else:

            working["satellite_encoded"] = -1

    # ------------------------------------------------------------------------
    # instrument_encoded
    # ------------------------------------------------------------------------

    if "instrument_encoded" in working.columns:

        working["instrument_encoded"] = pd.to_numeric(
            working["instrument_encoded"],
            errors="coerce",
        )

    else:

        instrument_column = _find_first_column(
            working,
            [
                "instrument",
            ],
        )

        if instrument_column is not None:

            working["instrument_encoded"] = _encode_categorical(
                working[instrument_column],
                {
                    "MODIS": 0,
                    "VIIRS": 1,
                },
                default_value=-1,
            )

        else:

            working["instrument_encoded"] = -1

    # ------------------------------------------------------------------------
    # type_encoded
    # ------------------------------------------------------------------------

    if "type_encoded" in working.columns:

        working["type_encoded"] = pd.to_numeric(
            working["type_encoded"],
            errors="coerce",
        )

    else:

        type_column = _find_first_column(
            working,
            [
                "type",
                "fire_type",
            ],
        )

        if type_column is not None:

            raw_type = pd.to_numeric(
                working[type_column],
                errors="coerce",
            )

            if raw_type.notna().any():
                working["type_encoded"] = raw_type
            else:
                categories = sorted(
                    _normalize_text(
                        working[type_column]
                    ).unique().tolist()
                )

                category_mapping = {
                    category: index
                    for index, category in enumerate(categories)
                }

                working["type_encoded"] = _encode_categorical(
                    working[type_column],
                    category_mapping,
                    default_value=-1,
                )

        else:

            working["type_encoded"] = -1

    # ------------------------------------------------------------------------
    # season_encoded
    # ------------------------------------------------------------------------
    # Existing encoded column is used when supplied.
    # Otherwise derive from month if available.
    #
    # Encoding:
    #   Winter = 0
    #   Spring = 1
    #   Summer = 2
    #   Autumn = 3
    # ------------------------------------------------------------------------

    if "season_encoded" in working.columns:

        working["season_encoded"] = pd.to_numeric(
            working["season_encoded"],
            errors="coerce",
        )

    else:

        month = None

        if "month" in working.columns:

            month = pd.to_numeric(
                working["month"],
                errors="coerce",
            )

        else:

            datetime_column = _find_first_column(
                working,
                [
                    "detection_timestamp",
                    "acq_datetime",
                    "datetime",
                    "timestamp",
                    "date_time",
                ],
            )

            if datetime_column is not None:

                parsed_datetime = pd.to_datetime(
                    working[datetime_column],
                    errors="coerce",
                )

                month = parsed_datetime.dt.month

        if month is None:

            working["season_encoded"] = -1

        else:

            working["season_encoded"] = np.select(
                [
                    month.isin([12, 1, 2]),
                    month.isin([3, 4, 5]),
                    month.isin([6, 7, 8]),
                    month.isin([9, 10, 11]),
                ],
                [
                    0,
                    1,
                    2,
                    3,
                ],
                default=-1,
            )

    # ------------------------------------------------------------------------
    # Final fixed feature matrix
    # ------------------------------------------------------------------------

    missing_features = [
        column
        for column in FEATURE_COLUMNS
        if column not in working.columns
    ]

    if missing_features:
        raise ValueError(
            "Could not prepare required features: "
            + ", ".join(missing_features)
        )

    features = working.loc[:, FEATURE_COLUMNS].copy()

    # Convert every feature to numeric.
    for column in FEATURE_COLUMNS:

        features[column] = pd.to_numeric(
            features[column],
            errors="coerce",
        )

    if features.isna().any().any():

        nan_columns = (
            features.columns[
                features.isna().any()
            ]
            .tolist()
        )

        raise ValueError(
            "Prepared feature matrix contains missing/invalid values in: "
            + ", ".join(nan_columns)
        )

    if not np.isfinite(
        features.to_numpy(dtype=float)
    ).all():

        raise ValueError(
            "Prepared feature matrix contains non-finite values."
        )

    return features


# ============================================================================
# PRODUCTION SERVICE
# ============================================================================

class RealFirmsProductionService:
    """
    Reusable production inference service.

    Models and thresholds are loaded during initialization and reused for
    subsequent predictions.
    """

    def __init__(
        self,
        model_dir: Union[str, Path] = MODEL_DIR,
        threshold_config_path: Union[str, Path] = THRESHOLD_CONFIG_PATH,
    ) -> None:

        self.model_dir = Path(model_dir)
        self.threshold_config_path = Path(threshold_config_path)

        self.model_files = {
            "24h": self.model_dir
            / "fireguard_real_firms_sensor_only_24h_v1.joblib",

            "48h": self.model_dir
            / "fireguard_real_firms_sensor_only_48h_v1.joblib",

            "72h": self.model_dir
            / "fireguard_real_firms_sensor_only_72h_v1.joblib",
        }

        self.models: Dict[str, Any] = {}

        self.thresholds: Dict[str, float] = {}

        self._load_thresholds()
        self._load_models()
        self._validate_model_schemas()

    # ------------------------------------------------------------------------

    def _load_thresholds(self) -> None:

        if not self.threshold_config_path.exists():

            raise FileNotFoundError(
                "Threshold configuration not found: "
                f"{self.threshold_config_path}"
            )

        with open(
            self.threshold_config_path,
            "r",
            encoding="utf-8",
        ) as file:

            config = json.load(file)

        self.thresholds = _extract_thresholds(config)

    # ------------------------------------------------------------------------

    def _load_models(self) -> None:

        for horizon, model_path in self.model_files.items():

            if not model_path.exists():

                raise FileNotFoundError(
                    f"{horizon} model not found: {model_path}"
                )

            saved_object = joblib.load(model_path)

            model = _extract_model(saved_object)

            self.models[horizon] = model

    # ------------------------------------------------------------------------

    def _validate_model_schemas(self) -> None:
        """
        Basic feature-count validation against the approved schema.
        """

        expected_count = len(FEATURE_COLUMNS)

        for horizon, model in self.models.items():

            model_feature_count = None

            if hasattr(model, "n_features_in_"):
                model_feature_count = int(
                    model.n_features_in_
                )

            elif hasattr(model, "feature_names_in_"):
                model_feature_count = len(
                    model.feature_names_in_
                )

            if (
                model_feature_count is not None
                and model_feature_count != expected_count
            ):
                raise ValueError(
                    f"{horizon} model expects "
                    f"{model_feature_count} features, "
                    f"but production schema contains "
                    f"{expected_count}."
                )

    # ------------------------------------------------------------------------

    @property
    def feature_columns(self) -> List[str]:
        """
        Return the approved feature order.
        """

        return FEATURE_COLUMNS.copy()

    # ------------------------------------------------------------------------

    def predict(
        self,
        dataframe: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Run production inference.

        Returns a copy of the input dataframe with:
            prob_24h
            pred_24h
            prob_48h
            pred_48h
            prob_72h
            pred_72h

        The original dataframe is never modified.
        """

        features = prepare_real_firms_features(dataframe)

        result = dataframe.copy()

        for horizon in ["24h", "48h", "72h"]:

            model = self.models[horizon]

            threshold = self.thresholds[horizon]

            probabilities = model.predict_proba(
                features
            )[:, 1]

            probabilities = np.asarray(
                probabilities,
                dtype=float,
            )

            if not np.isfinite(probabilities).all():

                raise ValueError(
                    f"{horizon} model produced non-finite probabilities."
                )

            if (
                probabilities.min() < 0.0
                or probabilities.max() > 1.0
            ):
                raise ValueError(
                    f"{horizon} model produced probabilities "
                    "outside [0, 1]."
                )

            predictions = (
                probabilities >= threshold
            ).astype(int)

            result[f"prob_{horizon}"] = probabilities

            result[f"pred_{horizon}"] = predictions

        return result

    # ------------------------------------------------------------------------

    def predict_record(
        self,
        record: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Run production inference for one record.
        """

        input_dataframe = pd.DataFrame([record])

        result = self.predict(input_dataframe)

        output_columns = [
            "prob_24h",
            "pred_24h",
            "prob_48h",
            "pred_48h",
            "prob_72h",
            "pred_72h",
        ]

        return {
            column: (
                float(result.iloc[0][column])
                if column.startswith("prob_")
                else int(result.iloc[0][column])
            )
            for column in output_columns
        }

    # ------------------------------------------------------------------------

    def get_status(self) -> Dict[str, Any]:
        """
        Return service metadata without changing any model or dataset.
        """

        return {
            "status": "ready",
            "project": "FIREGUARD",
            "service": "REAL FIRMS PRODUCTION SERVICE V1",
            "feature_count": len(FEATURE_COLUMNS),
            "feature_columns": FEATURE_COLUMNS.copy(),
            "thresholds": self.thresholds.copy(),
            "models": {
                horizon: str(path)
                for horizon, path
                in self.model_files.items()
            },
            "retraining": False,
            "model_modification": False,
            "dataset_modification": False,
            "synthetic_data": False,
            "fabricated_labels": False,
        }


# ============================================================================
# SINGLETON HELPER
# ============================================================================

_default_service: Union[
    RealFirmsProductionService,
    None,
] = None


def get_production_service() -> RealFirmsProductionService:
    """
    Return a cached production service instance.

    Models are loaded only once per Python process.
    """

    global _default_service

    if _default_service is None:

        _default_service = RealFirmsProductionService()

    return _default_service


def run_production_inference(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """
    Convenience function for application/API integration.
    """

    service = get_production_service()

    return service.predict(dataframe)


def run_production_inference_record(
    record: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Convenience function for one-record inference.
    """

    service = get_production_service()

    return service.predict_record(record)


# ============================================================================
# STANDALONE SERVICE CHECK
# ============================================================================

if __name__ == "__main__":

    print("=" * 72)
    print("🔥 FIREGUARD — REAL FIRMS PRODUCTION SERVICE V1")
    print("=" * 72)

    print()
    print("Loading production service...")

    service = RealFirmsProductionService()

    status = service.get_status()

    print()
    print("STATUS")
    print("-" * 72)

    print(
        f"Feature count : {status['feature_count']}"
    )

    print()
    print("THRESHOLDS")

    print(
        f"24H : {status['thresholds']['24h']}"
    )

    print(
        f"48H : {status['thresholds']['48h']}"
    )

    print(
        f"72H : {status['thresholds']['72h']}"
    )

    print()
    print("MODELS")

    for horizon, path in status["models"].items():

        print(
            f"{horizon.upper()} : FOUND"
        )

    print()
    print("=" * 72)
    print("STATUS: 🟢 PRODUCTION SERVICE READY")
    print("READY FOR: APPLICATION / API INTEGRATION")
    print("=" * 72)
